name: Build DLL from Zip Source

on:
  workflow_dispatch: # Cho phép khởi động workflow thủ công hoặc khi push
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn từ repository (nếu có)
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Tải file .zip từ repository (hoặc từ nguồn khác nếu cần)
      - name: Download Source Zip
        run: wget https://example.com/source.zip -O source.zip
        # Hoặc: `uses: actions/download-artifact@v2` nếu file .zip đã được lưu trong Artifacts

      # Bước 3: Giải nén file .zip
      - name: Unzip Source Files
        run: unzip source.zip -d source

      # Bước 4: Thiết lập môi trường .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'  # Chọn phiên bản .NET phù hợp với dự án

      # Bước 5: Khôi phục các thư viện phụ thuộc (dependencies)
      - name: Restore dependencies
        run: dotnet restore source

      # Bước 6: Build dự án để tạo file .dll
      - name: Build Project
        run: dotnet build source -c Release --no-restore

      # Bước 7: Xuất file .dll vào thư mục output
      - name: Publish DLL
        run: dotnet publish source -c Release -o ./output

      # Bước 8: Lưu file .dll dưới dạng Artifact
      - name: Upload DLL as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Built-DLL
          path: ./output
