name: Build MQTTnet DLL from Zip Source

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Giải nén file MQTTnet-4.3.7.1207.zip
      - name: Unzip Source Files
        run: unzip MQTTnet-4.3.7.1207.zip -d source

      # Bước 3: Thiết lập môi trường .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'  # Hoặc phiên bản phù hợp với MQTTnet

      # Bước 4: Khôi phục các thư viện phụ thuộc (dependencies)
      - name: Restore dependencies
        run: dotnet restore source

      # Bước 5: Build dự án để tạo file .dll
      - name: Build Project
        run: dotnet build source -c Release --no-restore

      # Bước 6: Xuất bản file .dll vào thư mục output
      - name: Publish DLL
        run: dotnet publish source -c Release -o ./output

      # Bước 7: Lưu file .dll dưới dạng Artifact
      - name: Upload DLL as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Built-DLL
          path: ./output
