name: Build DLL for MQTTnet

# Thiết lập sự kiện kích hoạt workflow, ví dụ, mỗi khi có thay đổi ở nhánh main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Định nghĩa các job sẽ chạy trong workflow
jobs:
  build:
    # Cài đặt môi trường (Ubuntu, nhưng có thể chọn Windows hoặc MacOS nếu cần)
    runs-on: ubuntu-latest

    # Các bước trong quy trình build
    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt .NET SDK (phiên bản phù hợp với thư viện, ví dụ .NET 5.0)
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      # Bước 3: Khôi phục các package cần thiết
      - name: Restore dependencies
        run: dotnet restore

      # Bước 4: Build dự án và tạo file .dll
      - name: Build project
        run: dotnet build -c Release --no-restore

      # Bước 5: Tạo file .dll trong thư mục output
      - name: Publish DLL
        run: dotnet publish -c Release -o ./output

      # Bước 6: Lưu trữ file .dll dưới dạng Artifact để tải về
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MQTTnet-DLL
          path: ./output
